[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dirtycrm"
version = "0.1.0"
description = "The quickest dirtiest crm"
authors = [{ name = "Alex Lance", email = "" }]
dependencies = []
